https://fews.net/global/food-assistance-outlook-brief/september-2026/print

In [13]:
import pandas as pd
import geopandas as gpd

In [3]:
df = pd.read_csv('/home/emily_zuetell/projects/poreallas/data/ipcFipe_data.csv')

In [ ]:
df = df[df['scenario']=='ML']
df = df[df['scenario']=='ML']

,source_organization,source_document,datasourcedocument,country,country_code,geographic_group,fewsnet_region,fnid,admin_0,admin_1,...,phase3_high_value,phase4_low_value,phase4_high_value,phase5_low_value,phase5_high_value,pct_rural_population,pct_urban_population,pct_displaced_population,key_drivers,areas_of_highest_concern
4,FEWS NET,Food Assistance Outlook Brief,6986,Afghanistan,AF,Southern Asia,Asia,AF,Afghanistan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,FEWS NET,Food Assistance Outlook Brief,6986,Afghanistan,AF,Southern Asia,Asia,AF,Afghanistan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,FEWS NET,Food Assistance Outlook Brief,6986,Afghanistan,AF,Southern Asia,Asia,AF,Afghanistan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,FEWS NET,Food Assistance Outlook Brief,6986,Afghanistan,AF,Southern Asia,Asia,AF,Afghanistan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,FEWS NET,Food Assistance Outlook Brief,6986,Burkina Faso,BF,Western Africa,West Africa,BF,Burkina Faso,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,FEWS NET,Food Assistance Outlook Brief,6986,Yemen,YE,Western Asia,Middle East and Europe,YE,Yemen,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
285,FEWS NET,Food Assistance Outlook Brief,6986,Zimbabwe,ZW,Southern Africa,Southern Africa,ZW,Zimbabwe,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
286,FEWS NET,Food Assistance Outlook Brief,6986,Zimbabwe,ZW,Southern Africa,Southern Africa,ZW,Zimbabwe,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
288,FEWS NET,Food Assistance Outlook Brief,6986,Zimbabwe,ZW,Southern Africa,Southern Africa,ZW,Zimbabwe,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,FEWS NET,Food Assistance Outlook Brief,6986,Zimbabwe,ZW,Southern Africa,Southern Africa,ZW,Zimbabwe,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
gdf = gpd.read_file("/home/emily_zuetell/projects/poreallas/data/ALL_HFIC/West Africa/WA_200907_CS.shp")

In [23]:
import os
import glob
def load_fewsnet_shapefiles(root_dir, countries):
    records = []
    for path in glob.glob(os.path.join(root_dir, "**", "*_CS.shp"), recursive=True):
        fname = os.path.basename(path).replace("_CS.shp", "")
        region, year, month = fname.split("_")[0], int(fname.split("_")[1][:4]), int(fname.split("_")[1][4:6])

        gdf = gpd.read_file(path)
        gdf["region"], gdf["year"], gdf["month"] = region, year, month
        if gdf.crs is None:
            gdf = gdf.set_crs("EPSG:4326")
        gdf = gdf.to_crs(countries.crs)

        joined = gpd.sjoin(gdf, countries, how="left", predicate="intersects")
        records.append(joined)
    return pd.concat(records, ignore_index=True)

In [19]:
def fetch_country_boundaries():
    url = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson"
    return gpd.read_file(url)[["NAME", "ADM0_A3", "geometry"]]

def join_to_countries(gdf, countries):
    return gpd.sjoin(gdf.to_crs(countries.crs), countries, how="left", predicate="intersects")

In [24]:
path = "/home/emily_zuetell/projects/poreallas/data/ALL_HFIC/"
countries = fetch_country_boundaries()
joined = load_fewsnet_shapefiles(path, countries)

In [29]:
joined[joined['year']==2015]

,CS,HA0,geometry,region,year,month,index_right,NAME,ADM0_A3,cov_start,...,ADMIN1,ADMIN2,ADMIN3,LZCODE,LZNAME,CS201201_P,CS201110_P,CS200910_P,HA,CS201010_P
0,1.0,0.0,"MULTIPOLYGON (((39.36784 -4.65351, 39.36945 -4...",EA,2015,10,66.0,Central African Rep.,CAF,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,0.0,"MULTIPOLYGON (((39.36784 -4.65351, 39.36945 -4...",EA,2015,10,176.0,S. Sudan,SDS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,0.0,"MULTIPOLYGON (((39.36784 -4.65351, 39.36945 -4...",EA,2015,10,15.0,Chad,TCD,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,0.0,"MULTIPOLYGON (((39.36784 -4.65351, 39.36945 -4...",EA,2015,10,11.0,Dem. Rep. Congo,COD,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,0.0,"MULTIPOLYGON (((39.36784 -4.65351, 39.36945 -4...",EA,2015,10,169.0,Rwanda,RWA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12639,88.0,0.0,"MULTIPOLYGON (((32.08669 -19.95787, 32.10582 -...",SA,2015,7,70.0,Zambia,ZMB,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12640,88.0,0.0,"MULTIPOLYGON (((32.08669 -19.95787, 32.10582 -...",SA,2015,7,72.0,Mozambique,MOZ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12641,88.0,99.0,"MULTIPOLYGON (((35.05438 -16.62605, 35.0587 -1...",SA,2015,7,70.0,Zambia,ZMB,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12642,88.0,99.0,"MULTIPOLYGON (((35.05438 -16.62605, 35.0587 -1...",SA,2015,7,72.0,Mozambique,MOZ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12643,88.0,99.0,"MULTIPOLYGON (((35.05438 -16.62605, 35.0587 -1...",SA,2015,7,71.0,Malawi,MWI,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN